django_tutorial/articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('index/',views.index),
    path('dinner/',views.dinner, name='dinner'),
    path('review/',views.review, name='review'),
    path('create_review/',views.create_review, name='create_review'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/delete',views.delete, name='delete'),
    path('<int:pk>/edit',views.edit, name='edit'),
    path('<int:pk>/update',views.update, name='update'),
]

django_tutorial/django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls'))
]

django_tutorial/articles/models.py
from django.db import models

class Article(models.Model): #상속
    # id는 자동으로 만들어진다
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

django_tutorial/foods/models.py
from django.db import models

# Create your models here.

django_tutorial/articles/views.py
from django.shortcuts import render, redirect
import random
from .models import Article
# Create your views here.
def index(request):
    return render(request,'index.html')

def dinner(request):
    menus = [{"name":"족발","price":30000},{"name":"햄버거","price":5000},{"name":"치킨","price":25000}]
    pick = random.choice(menus)
    articles = Article.objects.order_by('-pk') # -pk 역순
    context = {
        'pick':pick,
        'menus':menus,
        'articles':articles,
    }
    return render(request,'dinner.html',context)

def review(request):
    return render(request, 'review.html')

def create_review(request):
    content = request.POST.get('content')
    title = request.POST.get('title')
    article = Article(title=title, content=content)
    article.save() # db에 알아서 저장
    return redirect("articles:detail",article.pk)

def detail(request,pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article':article
    }
    return render(request, 'detail.html',context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    
    if request.method =='POST':
        article.delete()

    return redirect("articles:dinner")

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context={
        'article':article
    }
    return render(request,'edit.html',context)

def update(request,pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get("title")
    article.content = request.POST.get("content")
    article.save()
    return redirect('articles:detail',article.pk)

django_tutorial/foods/views.py
from django.shortcuts import render

# Create your views here.

django_tutorial/articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>오늘 뭐먹지?</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="container">
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

django_tutorial/articles/templates/detail.html
{% extends 'base.html' %}{% block content %}
<h2 class = 'text-center'>DETAIL</h2>
<h3>{{article.pk}}</h3>
<hr>
<p>제목 : {{article.title}}</p>
<p>내용 : {{article.content}}</p>
<p>작성 시각 : {{article.created_at|date:"SHORT_DATE_FORMAT"}}</p>
<form class='form-group' action="{% url 'articles:delete' article.pk %}", method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">DELETE</button>
</form>
<a href="{% url 'articles:edit' article.pk %}" class="btn btn-primary">[EDIT]</a><br>
<a href="{% url 'articles:dinner' %}">[BACK]</a>
<hr>
{% endblock %}

django_tutorial/articles/templates/dinner.html
{% extends 'base.html' %} {% block content %}
<h1>오늘 님의 저녁은 {{pick.name}}입니다.</h1>
<h1>메뉴 리스트</h1>
<ul>
    {% for menu in menus %}
    <li>{{menu.name}} {{menu.price}}원</li>
    {% endfor %}
</ul>

<h1>리뷰 리스트</h1>
<a href="{% url 'articles:review' %}">[리뷰 작성하기]</a>
{% for article in articles %}
<p>글 번호 : {{article.pk}} </p>
<p>글 제목 : {{article.title}}</p>
<p>글 내용 : {{article.content}}</p>
<a href="{% url 'articles:detail' article.pk %}">[detail]</a>
<hr>
{% endfor %}

{% endblock %}

django_tutorial/articles/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">EDIT</h1>
<form 
    class='form-group' 
    action="{% url 'articles:update' article.pk %}" 
    method="POST"
>
    {% csrf_token %}
    <label for="title">Title</label>
    <input class="form-control" type="text" name='title' value ="{{ article.title }}" ><br>
    <label for="content">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5">{{ article.content }}</textarea><br>
    <input type="submit">
</form>

{% endblock %}

django_tutorial/articles/templates/review.html
{% extends 'base.html' %}
{% block content %}
<form class='form-group' action = "{% url 'articles:create_review' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title</label>
    <input class='form-control' type="text" name='title' ><br>
    <label for="content">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5"></textarea><br>
    <input type="submit">
</form>
{% endblock %}

django_tutorial/articles/templates/review_result.html
<h1>보내서 받은내용{{content}}야!!</h1>